# Start of the dashboard ui-lovelace.yaml
card_mod:
  global: |
    /* Global feature height for all cards */
    hui-card-features {
      --feature-height: 20px !important;
    }

    /* Global slider styling for all sliders */
    ha-control-slider,
    ha-control-slider::part(container),
    ha-slider,
    ha-slider::part(track),
    ha-slider::part(handle) {
      --control-slider-thickness: 20px !important;
    }
#Load all settings for Dashboard
dwains_dashboard:
  active: true

#For people who want to use button card templates
button_card_templates: 
  !include_dir_merge_named ../../../dwains-dashboard/button_card_templates

#For people who want to use apexcharts card templates
apexcharts_card_templates:
  !include_dir_merge_named ../../../dwains-dashboard/apexcharts_card_templates

# Start of main lovelace theme 
lovelace-background: var(--background-image)
views:
  !include_dir_merge_list views/

